// Media Hub — extension bridge client.
//
// Shared helper used by popup.js + background.js (service worker).
// Wraps:
//   - reading the configured URL + token from chrome.storage.local
//   - POST /enqueue with the bearer header
//   - GET /health for the popup status pill
//   - building a mediahub:// fallback URL for the "app not running"
//     case (tab.open redirect lets the OS launch the app)
//
// No dependencies — runs identically in MV3 service workers (no DOM)
// and in popup pages (DOM available). Everything async, no top-level
// state; the popup re-fetches settings on each open so live edits in
// the options page take effect immediately.

export const DEFAULT_URL = "http://127.0.0.1:47821";

// 1.7.x — cookie-bridge. Read the target site's cookies (incl. httpOnly
// auth tokens, which document.cookie can't see) via the cookies API and
// serialize to Netscape cookies.txt for yt-dlp. The desktop caches it
// per-platform so restricted/age-gated downloads use a live logged-in
// session — no manual export, never stale.
//
// Lives here (not just background.js) so EVERY send path — popup,
// context menu, hotkey, overlay — harvests automatically via enqueue().
// Scoped to the target site only; we never ship the whole jar. YouTube
// is special-cased: its auth tokens also live on .google.com. Returns ""
// on any failure so a cookie hiccup never blocks the send.
export async function harvestCookies(target) {
  try {
    if (!chrome?.cookies || !/^https?:/i.test(target)) return "";
    // Consent gate — we never read the user's login cookies until they've
    // opted in (popup first-run consent / Sync button). Until then every
    // send goes cookie-free.
    const { cookieConsent } = await chrome.storage.local.get("cookieConsent");
    if (!cookieConsent) return "";
    let host = "";
    try {
      host = new URL(target).hostname.toLowerCase();
    } catch {
      return "";
    }
    const jars = [];
    jars.push(await chrome.cookies.getAll({ url: target }));
    if (host.includes("youtube") || host.includes("youtu.be")) {
      jars.push(await chrome.cookies.getAll({ domain: "google.com" }));
    }
    const seen = new Set();
    const lines = [
      "# Netscape HTTP Cookie File",
      "# Generated by Media Hub extension",
    ];
    for (const jar of jars) {
      for (const c of jar || []) {
        const key = `${c.domain}|${c.path}|${c.name}`;
        if (seen.has(key)) continue;
        seen.add(key);
        const includeSub = c.hostOnly ? "FALSE" : "TRUE";
        const secure = c.secure ? "TRUE" : "FALSE";
        const expiry = c.session ? 0 : Math.floor(c.expirationDate || 0);
        lines.push(
          [c.domain, includeSub, c.path || "/", secure, expiry, c.name, c.value].join("\t"),
        );
      }
    }
    return lines.length > 2 ? lines.join("\n") + "\n" : "";
  } catch (e) {
    console.warn("[mh] cookie harvest failed:", e);
    return "";
  }
}

/** Load { url, token } from extension storage. Token may be empty
 *  on first run — the popup prompts the user to open Options. */
export async function loadConfig() {
  const stored = await chrome.storage.local.get(["bridgeUrl", "bridgeToken"]);
  return {
    url: (stored.bridgeUrl || DEFAULT_URL).replace(/\/+$/, ""),
    token: stored.bridgeToken || "",
  };
}

export async function saveConfig({ url, token }) {
  await chrome.storage.local.set({
    bridgeUrl: (url || DEFAULT_URL).trim(),
    bridgeToken: (token || "").trim(),
  });
}

/** Ping /health. Returns { ok: true, version } on success, or
 *  { ok: false, error } on any failure (network, non-2xx, etc.).
 *  Used by the popup to show a connection indicator. */
export async function pingHealth(url) {
  try {
    const res = await fetch(`${url}/health`, {
      method: "GET",
      headers: { Accept: "application/json" },
    });
    if (!res.ok) return { ok: false, error: `HTTP ${res.status}` };
    const json = await res.json();
    return { ok: true, version: json.version || "?" };
  } catch (e) {
    return { ok: false, error: String(e?.message || e) };
  }
}

/** POST a URL into the queue. Returns { ok: true } on 2xx, or
 *  { ok: false, error, status } on anything else. Caller decides
 *  what to do — popup shows toast, background shows a notification. */
export async function enqueue({ url, token, target, audioFormat, projectId, source, cookies, quality, transcode, rename }) {
  if (!url) return { ok: false, error: "bridge URL not configured" };
  if (!token) return { ok: false, error: "bridge token not configured" };
  if (!target) return { ok: false, error: "no URL to send" };

  const body = {
    url: target,
    source: source || "extension",
  };
  if (audioFormat) body.audio_format = audioFormat;
  if (projectId) body.project_id = projectId;
  // 1.13.x — extension quick-menu overrides (optional).
  if (quality) body.quality = quality;
  if (transcode && transcode !== "none") body.transcode = transcode;
  if (rename && rename.trim()) body.rename = rename.trim();
  // 1.7.x — cookie-bridge: attach a fresh Netscape cookies.txt for the
  // target site. Caller may pass `cookies` explicitly; otherwise we
  // harvest here so every send path benefits without extra wiring.
  const cookieBlob = cookies !== undefined ? cookies : await harvestCookies(target);
  if (cookieBlob) body.cookies = cookieBlob;

  try {
    const res = await fetch(`${url}/enqueue`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(body),
    });
    if (res.ok) return { ok: true };
    let detail = `HTTP ${res.status}`;
    try {
      const j = await res.json();
      if (j && j.error) detail = j.error;
    } catch {
      /* non-JSON error body */
    }
    return { ok: false, error: detail, status: res.status };
  } catch (e) {
    // Most common reason: app not running. The popup catches this
    // and offers the mediahub:// deep-link fallback which the OS
    // resolves even when the app is offline.
    return { ok: false, error: String(e?.message || e), offline: true };
  }
}

// Supported sites the "Sync cookies" button warms in one click. Each is
// a representative URL we harvest cookies for.
export const SYNC_SITES = [
  ["YouTube", "https://www.youtube.com/"],
  ["Instagram", "https://www.instagram.com/"],
  ["Twitter / X", "https://x.com/"],
  ["TikTok", "https://www.tiktok.com/"],
  ["Reddit", "https://www.reddit.com/"],
  ["Pinterest", "https://www.pinterest.com/"],
  ["Facebook", "https://www.facebook.com/"],
];

/** Harvest cookies for every supported site the user is logged into and
 *  push them to the desktop cache (POST /cookies) — no download. Returns
 *  { synced: [labels], offline?: bool }. The caller must have granted
 *  cookieConsent first (harvestCookies enforces it). */
export async function syncCookies({ url, token }) {
  if (!url || !token) return { synced: [], error: "bridge not configured" };
  const synced = [];
  let offline = false;
  for (const [label, siteUrl] of SYNC_SITES) {
    const blob = await harvestCookies(siteUrl);
    if (!blob) continue; // not logged in / no cookies / no consent
    try {
      const res = await fetch(`${url}/cookies`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ url: siteUrl, cookies: blob }),
      });
      if (res.ok) synced.push(label);
    } catch {
      offline = true;
      break;
    }
  }
  return { synced, offline };
}

/** Build a mediahub:// deep-link URL the OS can launch even when the
 *  app isn't running. Same query-param shape the Rust deep-link
 *  parser expects (lib.rs::parse_deeplink_url). */
export function buildDeepLink({ token, target, audioFormat, projectId }) {
  const params = new URLSearchParams();
  params.set("url", target);
  params.set("token", token || "");
  if (audioFormat) params.set("audio_format", audioFormat);
  if (projectId) params.set("project_id", projectId);
  return `mediahub://enqueue?${params.toString()}`;
}
